### ISSUE TITLE
Console warning when bootstrap vue component <b-form-select> is populated in vue form generator.

### ISSUE THREAD

**Issue by abhilashtg** [vue-generators/vue-form-generator#610]
* **I'm submitting a bug report.**

Following warning in the log:

[Vue warn]: **Error in directive model inserted hook: "TypeError: this.each is not a function"**

found in

---> 

```
 <BFormSelect>
        <FieldComboRashes>
         <FormGroup>
            <FormGenerator>
              <Root>
```

I am trying to use `<b-form-select>` for showing a select box in the vfg, as a custom component. The fields/model for vfg are loaded at the time of mounted hook.

The select is coming correctly and the options are also showing.

When i select an option, the warning message in console is:

**[Vue warn]: Error in directive model componentUpdated hook: "TypeError: this.each is not a function"** found in --->

>  `<BFormSelect> <FieldComboRashes> <FormGroup> <FormGenerator> <Root>`

**Comment by zoul0813** [comment]
This does not appear to be a bug in VFG, and looks like an issue with your custom component, which we can’t support.  Please use StackOverflow to get help with creating a custom component.

If you have identified a bug in VFG, please be specific about it.

Closing this issue for now - feel free to reopen if you’ve tracked the issue down to something specific within VFG.

**Comment by abhilashtg** [comment]
Yes...found to be a conflict with rico.js and prototype.js, when b-form-select was used.

**Comment by kiatng** [comment]
Thanks for the finding on prototype.js. After upgrading it to 1.7.3, it seems to resolve the conflict.
